version: "3.5"

services:
  traefik_init:
    image: traefik:1.7
    command:
      - storeconfig
      - --api 
      - --api.dashboard=true
      - --docker
      - --docker.swarmMode=true
      - --docker.watch=true 
      - --docker.exposedbydefault=false 
      - --docker.domain=${DOMAIN}
      - --docker.network=web 
      - --debug=false
      - --logLevel=INFO
      - --accessLog.format=json
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --insecureSkipVerify=true
      #- --acme
      #- --acme.email=infra@complemento.net.br
      #- --acme.storage=traefik/acme/account
      #- --acme.entryPoint=https
      #- --acme.onHostRule=true
      #- --acme.httpchallenge.entrypoint=http
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
      
  traefik:
    image: traefik:1.7
    depends_on:
      - traefik_init
      - consul
    command:
      - --logLevel=INFO
      - --accessLog.format=json
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.frontend.rule=Host:balanceador.{DOMAIN}
        - traefik.protocol=http
        - traefik.docker.network=web
        - traefik.frontend.auth.basic.users=${ADMIN_USER}:${HASHED_PASSWORD}
        
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"local","server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik
      
networks:
  web:
    driver: overlay
    external: true
  traefik:
    driver: overlay

volumes:
  consul-data:
      driver: local
