version: '3.8'

services:
  server:
    image: traefik:v1.7
    command: 
      - --api 
      - --docker
      - --docker.swarmMode
      - --docker.watch=true 
      - --docker.exposedbydefault=false 
      - --docker.domain=${DOMAIN} 
      - --docker.network=web 
      - --debug=false
      - --logLevel=INFO
      #- --accessLog.filePath="/log/access.log"
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      #- --entryPoints=Name:https Address::443 TLS:/ssl/host.crt,/ssl/host.key
      #- --acme
      #- --acme.email=${ACME_EMAIL}
      #- --acme.storage=/ssl/acme.json
      #- --acme.entryPoint=https
      #- --acme.onHostRule=true
      #- --acme.httpchallenge.entrypoint=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssl:/ssl
      - log:/log
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  web:
    external: true
    name: web
  #web:
  #  driver: overlay
  #  attachable: true

volumes:
  log:
    driver: local
  ssl:
    driver: local


