version: '3.8'

services:
  pma: 
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: https://${WEBSERVER_FQDN}/pma/
      #PMA_HOSTS: dbtest_database,dbreplica_database
      PMA_HOSTS: 
    networks:
      #- dbnet1
      - web
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${WEBSERVER_FQDN};PathPrefixStrip:/pma
      - traefik.protocol=http
      - traefik.docker.network=web
      #- traefik.frontend.auth.basic.users=pma:<pwdhash>
            
networks:
  dbnet1:
    external: true
    name: dbnet1_default
  web:
    external: true
    name: ${PROXY_NET:-proxy}
